<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNl1AmNh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNl1AmNh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNl1AmNh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNl1AmNh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNl1AmNh\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nl1AmNh',
    'container.build_id' => '2f3ad9c6',
    'container.build_time' => 1607275167,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNl1AmNh');
